title: Repositório de Poemas
owner: Olivia Janequine
email:
description: Arquivamento, publicação e desenvolvimento de poemas
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://olivia-olivia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
language: pt
twitter_username: oliviagj
github_username: olivia-olivia
disqus_username:
# Build settings
markdown: kramdown
theme: minima

permalink: /:year-:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
