title: Repositório de Poemas
owner: Olivia Janequine
email:
description: Arquivamento, publicação e desenvolvimento de poemas
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://poeta.olivia.click" # the base hostname & protocol for your site, e.g. http://example.com
language: pt
twitter_username: oliviagj
github_username: olivia-olivia
disqus_username:
# Build settings
markdown: kramdown
theme: minima

permalink: /:year-:title/

plugins:
  - jekyll-feed

excerpt_separator: <!--more-->
